baseURL = 'https://sandrorgguimaraes.github.io/'
contentDir = "content/pt-br"
languageCode = 'pt-br'
defaultContentLanguage = "pt-br"
defaultContentLanguageInSubdir = false
title = 'Diário de Bordo'
theme = "docsy"

[taxonomies]
tag = "tags"
category = "categories"
autor = "autores"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories", "autores"] 
# If used, must have same lang as taxonomyCloud
taxonomyCloudTitle = ["Tags", "Categorias", "Autores"] 
# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories", "autores"] 

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[params]
time_format_default = "2 de Jan de 2006"
time_format_blog = "2 de Jan de 2006"
copyright = "Sandro Rogério Galvão Guimarães"
#privacy_policy = "https://policies.google.com/privacy"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
#github_repo = "https://github.com/google/docsy-example"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
#github_project_repo = "https://github.com/google/docsy"

# <script async src="https://cse.google.com/cse.js?cx=00d233acb080f4e82">
# </script>
# <div class="gcse-search"></div>
gcs_engine_id = "00d233acb080f4e82"
# Enable Algolia DocSearch
algolia_docsearch = false
# Enable Lunr.js offline search
offlineSearch = false

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
# Set menu foldable
sidebar_menu_foldable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Fico feliz em ouvi-lo! Por favor, <a href="https://github.com/USERNAME/REPOSITORY/issues/new">diga-nos como podemos melhorar</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/sandrorgguimaraes/"
  icon = "fab fa-linkedin"
[[params.links.user]]
  name = "Twitter"
  url = "https://www.twitter.com/sandrorogerio/"
  icon = "fab fa-twitter-square"
[[params.links.user]]
  name = "GitHub"
  url = "https://github.com/sandrorgguimaraes/"
  icon = "fab fa-github-square"
